#!/bin/sh

# print config if requested
case $1 in
   config)
        cat << 'EOM'
graph_title Humidity
graph_vlabel humidity[%]
graph_category am2321
graph_info Humidity measured with Aosong's AM2321 sensor.
humidity.label humidity
humidity.info Humidity measured with AM2321.
EOM

        exit 0;;
esac

# measure temperature and humidity with am2321
temp_humid=`sleep 2; /home/pi/am2321/am2321` || exit 1

# print humidity in Munin plugin format
printf "humidity.value "; echo $temp_humid | cut -d ' ' -f2
